/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2009
 * 
 * XDoclet definition:
 * @struts.form name="logForm"
 */
public class logForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** num property */
	private String num;

	/** usr property */
	private String usr;

	/** pwd property */
	private String pwd;
	
	private String lasturl;

	private String forwardurl;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the num.
	 * @return String
	 */
	public String getNum() {
		return num;
	}

	/** 
	 * Set the num.
	 * @param num The num to set
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/** 
	 * Returns the usr.
	 * @return String
	 */
	public String getUsr() {
		return usr;
	}

	/** 
	 * Set the usr.
	 * @param usr The usr to set
	 */
	public void setUsr(String usr) {
		this.usr = usr;
	}

	/** 
	 * Returns the pwd.
	 * @return String
	 */
	public String getPwd() {
		return pwd;
	}

	/** 
	 * Set the pwd.
	 * @param pwd The pwd to set
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getLasturl() {
		return lasturl;
	}

	public void setLasturl(String lasturl) {
		this.lasturl = lasturl;
	}

	public String getForwardurl() {
		return forwardurl;
	}

	public void setForwardurl(String forwardurl) {
		this.forwardurl = forwardurl;
	}
}