/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2009
 * 
 * XDoclet definition:
 * @struts.form name="regForm"
 */
public class regForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** num property */
	private String num;

	/** email property */
	private String email;

	/** usr property */
	private String usr;

	/** repwd property */
	private String repwd;

	/** pwd property */
	private String pwd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the num.
	 * @return String
	 */
	public String getNum() {
		return num;
	}

	/** 
	 * Set the num.
	 * @param num The num to set
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the usr.
	 * @return String
	 */
	public String getUsr() {
		return usr;
	}

	/** 
	 * Set the usr.
	 * @param usr The usr to set
	 */
	public void setUsr(String usr) {
		this.usr = usr;
	}

	/** 
	 * Returns the repwd.
	 * @return String
	 */
	public String getRepwd() {
		return repwd;
	}

	/** 
	 * Set the repwd.
	 * @param repwd The repwd to set
	 */
	public void setRepwd(String repwd) {
		this.repwd = repwd;
	}

	/** 
	 * Returns the pwd.
	 * @return String
	 */
	public String getPwd() {
		return pwd;
	}

	/** 
	 * Set the pwd.
	 * @param pwd The pwd to set
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
}